AWSTemplateFormatVersion: 2010-09-09
Description: CloudFormation template primitive which creates Route 53 Private Hosted Zone.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Zone Details
        Parameters:
          - ZoneName
          - ZoneComment
          - VpcId
          - VpcRegion
      - Label:
          default: Tags
        Parameters:
          - EnvironmentId
          - ProjectId
          - Contact
          - CostCenter 
          - Confidentiality
          - Compliance
Parameters:
  ZoneName:
    Type: String
    Default: foo.domain.com
  VpcId:
    Description: VPC in which this zone will be resolved. One included by default. Modify template if more VPCs required. AWS CLI commands required to share to VPCs in other accounts.
    Type: String
  VpcRegion:
    Description: VPC Region.
    Type: String
  ZoneComment:
    Description: Zone Comment
    Type: String
    Default:  "Private Hosted Zone"
  EnvironmentId:
    Type: String
    Default: dev
  ProjectId:
    Type: String
    Default: ProjectId
  CostCenter:
    Type: String
    Description: The CostCenter tag is used to designate the cost center associated with the project of the given AWS resource.
    Default: 0000
    AllowedPattern: "^[a-zA-Z0-9]+$"
    ConstraintDescription:  provide a valid cost center
  Contact:
    Type: String
    Default: user@domain.com
    Description: The Contact tag is used to designate business owner(s) email address associated with the given AWS resource for sending outage or maintenance notifications
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: provide a valid email address.
  Confidentiality:
    Type: String
    Description: The Confidentiality tag is used to designate the confidentiality classification of the data that is associated with the resource.
    Default: private
    AllowedValues:
      - public
      - private
      - confidential
      - pii/phi
  Compliance:
    Type: String
    Description: The Compliance tag is used to specify the Compliance level for the AWS resource.
    Default: none
    AllowedValues:
      - hipaa
      - sox
      - fips
      - gxp
      - other
      - none
Resources:
  Route53HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref ZoneName
      HostedZoneConfig:
        Comment: !Ref ZoneComment
      VPCs: 
        - VPCId: !Ref VpcId
          VPCRegion: !Ref VpcRegion
      HostedZoneTags:
        - Key: Name
          Value: !Ref ZoneName
        - Key: EnvironmentId
          Value: !Ref EnvironmentId
        - Key: Contact
          Value: !Ref Contact
        - Key: ProjectId
          Value: !Ref ProjectId
        - Key: Confidentiality
          Value: !Ref Confidentiality
        - Key: Compliance
          Value: !Ref Compliance
        - Key: CostCenter
          Value: !Ref CostCenter
Outputs:
  Route53HostedZoneId:
    Description: The ID of the Private Hosted Zone
    Value: !Ref Route53HostedZone
    Export:
      Name: !Sub "${AWS::StackName}-id"