AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFormation template primitive which creates an S3 bucket resource.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Network Parameters
        Parameters:
          - BucketName
          - AccessControl
          - KmsMasterKeyId
          - SseAlgorithm
          - VersioningConfiguration
      - Label:
          default: Environment and Tags
        Parameters:
          - EnvironmentId
          - Contact
          - ProjectId
          - CostCenter
          - Confidentiality
          - Compliance
Parameters:
  EnvironmentId:
    Type: String
    Default: dev
  ProjectId:
    Type: String
    Default: ProjectId
  Contact:
    Type: String
    Description: The Contact tag is used to designate business owner(s) email address associated with the given AWS resource for sending outage or maintenance notifications
    Default: user@domain.com
    AllowedPattern: '^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$'
    ConstraintDescription: provide a valid email address.
  CostCenter:
    Type: String
    Description: The CostCenter tag is used to designate the cost center associated with the project of the given AWS resource.
    Default: 0000
    AllowedPattern: "^[a-zA-Z0-9]+$"
    ConstraintDescription:  provide a valid cost center
  Confidentiality:
    Type: String
    Description: The Confidentiality tag is used to designate the confidentiality classification of the data that is associated with the resource.
    Default: private
    AllowedValues:
      - public
      - private
      - confidential
      - pii/phi
  Compliance:
    Type: String
    Description: The Compliance tag is used to specify the Compliance level for the AWS resource.
    Default: other
    AllowedValues:
      - hipaa
      - sox
      - fips
      - gxp
      - other
      - none
  AccessControl:
    Description: Canned ACL. Default is Private, and should not be changed unless you know exactly why you're changing it. See https://docs.aws.amazon.com/AmazonS3/latest/dev/acl-overview.html#canned-acl
    Default: Private
    AllowedValues:
      - AuthenticatedRead
      - AwsExecRead
      - BucketOwnerRead
      - BucketOwnerFullControl
      - LogDeliveryWrite
      - Private
      - PublicRead
      - PublicReadWrite
    Type: String
  AccelerationStatus:
    Description: Sets S3 bucket acceleration status. Default should be Suspended. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-accelerateconfiguration.html
    AllowedValues:
      - Enabled
      - Suspended
    Type: String
    Default: Suspended
  BucketName:
    Description: Sets S3 bucket name. If left blank, name will be autogenerated. Default is blank.
    Type: String
    Default: ""
  KmsMasterKeyId:
    Description: Leave blank unless SseAlgorithm is set to aws:kms *and* you want to use your own custom key.
    Type: String
    Default: ""
  SseAlgorithm:
    Type: String
    Default: AES256
    Description: Default S3 encryption algorithm to use. Leave at the default value of AES256 unless you want to incur KMS charges.
    AllowedValues:
      - AES256
      - aws:kms
  VersioningConfiguration:
    Description: Sets S3 bucket versioning. Default is Enabled. See https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-s3-bucket-versioningconfig.html
    AllowedValues:
      - Enabled
      - Suspended
    Type: String
    Default: Enabled
Conditions:
  HasBucketName: !Not [!Equals [!Ref BucketName, ""]]
  HasKmsMasterKeyId: !Not [!Equals [!Ref KmsMasterKeyId, ""]]
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: !Ref AccessControl
      AccelerateConfiguration:
        AccelerationStatus: !Ref AccelerationStatus
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              KMSMasterKeyID: !If [HasKmsMasterKeyId, !Ref KmsMasterKeyId, !Ref "AWS::NoValue"]
              SSEAlgorithm: !Ref SseAlgorithm
      BucketName: !If [HasBucketName, !Ref BucketName, !Ref "AWS::NoValue"]
      Tags:
        - Key: EnvironmentId
          Value: !Ref EnvironmentId
        - Key: Contact
          Value: !Ref Contact
        - Key: ProjectId
          Value: !Ref ProjectId
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Confidentiality
          Value: !Ref Confidentiality
        - Key: Compliance
          Value: !Ref Compliance
      VersioningConfiguration:
        Status: !Ref VersioningConfiguration
    DeletionPolicy: Delete
Outputs:
  BucketName:
    Value: !Ref 'S3Bucket'
    Description: Name of the Amazon S3 bucket.
    Export:
      Name: !Sub ${AWS::StackName}-bucket
